FROM python:3.12-slim


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    netcat-openbsd \
    gcc \
    libpq-dev \
    && apt-get clean

#Install Python Dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy Project Code
COPY . /app/

# Copy Entrypoint & Fix Permissions
COPY entrypoint.sh /app/
RUN chmod +x /app/entrypoint.sh

# Run Entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]